version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: "true"
