version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - composer

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["composer", "install", "--no-dev", "--optimize-autoloader"]
